const Languages = {
    en:{
        allDone: "All Done!",
        back: "Back",
        birthDatePlaceholder: "Birth Date",
        call: "Call",
        cancel: "Cancel",
        chat: "Chat",
        changePassword: "Change Password",
        cctv: "CCTV",
        contactHFM: "Contact HFM",
        confirmNewPasswordPlaceholder: "Re-enter new password",
        currentPasswordPlaceholder: "Enter current password",
        date: "Date",
        dontHaveAccount: "Don't have an account?",
        dontHaveAccountAlertTitle: "No Account?",
        dontHaveAccountAlertDesc: "If you have no account email us or phone us.",
        dontHaveAccountAlertOkBtn: "Ok",
        dontHaveAccountAlertEmailBtn: "Email",
        dontHaveAccountAlertPhoneBtn: "Phone",
        editProfile: "Edit Profile",
        email: "Email",
        emailAddress: "Email Address",
        emailAddressPlaceholder: "Enter your email address",
        feedback: "Feedback",
        feedbackTitle: "Thank you for using our app!",
        feedbackDesc: "Please rate your experience",
        feedbackContactsDesc: "We would love to hear from you! If you have specific app feedback to leave for us please use the Feedback page.",
        forgotPassword: "Forgotten your password?",
        forgotPasswordTitle: "Reset Password",
        forgotPasswordDesc: "Please enter the email associated with your account and we’ll mail you a link to reset your password.",
        home: "Home",
        games: "Games",
        genderPlaceholder: "Gender",
        goToFeedback: "Go To Feedback",
        leaveComment: "Leave a comment (optional)",
        locationPlaceholder: "Address",
        loginSuccessTitle: "Congratulations!",
        loginSuccessMessage: "You have successfully signed in, you will now be redirected to the home screen, we hope you enjoy the app.",
        makevideocall: "Make a Video Call",
        more: "More",
        myaccount: "My Account",
        firstNamePlaceholder: "Enter your first name",
        lastNamePlaceholder: "Enter your last name",
        newPasswordPlaceholder: "Enter new password",
        or: "or",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        playgames: "Play Games",
        phonePlaceholder: "Enter your  Phone Number",
        privacyPolicy: "Privacy Policy",
        profile: "Profile",
        saveProfile: "Save Profile",
        saveNewPassword: "Save New Password",
        search: "Search",
        service: "Service",
        signIn: "Sign In",
        signout: "Sign Out",
        sendFeedback: "Send Feedback",
        spending: "Spending",
        spent: "Spent",
        termsprivacy: "Terms & Privacy",
        termsUse: "Terms of Use",
        termsConditions: "Terms & Conditions",
        total: "Total",
        videocall: "Video Call",
        viewinternalcctv: "View Internal CCTV",
        resetPassword: "Reset Password",
        resetPasswordDesc: "A link to reset your password has been sent to your email address.",
    }
};

export default Languages;